### PR TITLE
IXUAT-5067 Dealing with invalid version numbers

### PR DESCRIPTION
**Pull request by timrog1**

### CODE REVIEW

**Comment by taliesins** [comment]
Could we get a unit test that demonstrated the problem and the fix. Maybe off the GetBranchesMethod?

I think we may have a problem here too:
https://github.com/Aqovia/OctopusPuppet/blob/365b1376bbcfd2c3b2db86792e59174ccbe15720/src/OctopusPuppet.OctopusProvider/OctopusDeploymentPlanner.cs#L179

**Comment by timrog1** [comment]
Do you want to set a timebox for this? There aren't any unit tests round this currently, so it's going to involve a certain amount of rewriting, and it doesn't strike me as the highest priority.

**Comment by ma499** [comment]
Fair point. Maybe 1-2 hours? Might be easiest to just make some of the currently private methods public for very narrow test coverage and then evolve over time?

**Comment by ma499** [comment]
More importantly Taliesin is worried about line 179 of OctopusDeploymentPlanner.cs (but I can't see how to get Github review to record a comment on an unchanged line.

**Pull request merged**
